<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Maps\MappingProfile.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FVN_REGISTER.Core\FVN_REGISTER.Core.csproj" />
    <ProjectReference Include="..\FVN_REGISTER.Models\FVN_REGISTER.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Infrastructure\" />
  </ItemGroup>

</Project>
