using Blazored.LocalStorage;
using FVN_REGISTER.Application.Configuration;
using FVN_REGISTER.Shared.Handlers;
using FVN_REGISTER.Shared.Services.Approvals;
using FVN_REGISTER.Shared.Services.Calendar;
using FVN_REGISTER.Shared.Services.Execution;
using FVN_REGISTER.Shared.Services.Dashboards;
using FVN_REGISTER.Shared.Services.Departments;
using FVN_REGISTER.Shared.Services.Emails;
using FVN_REGISTER.Shared.Services.Employees;
using FVN_REGISTER.Shared.Services.Histories;
using FVN_REGISTER.Shared.Services.History;
using FVN_REGISTER.Shared.Services.HrmSync;
using FVN_REGISTER.Shared.Services.Leaves;
using FVN_REGISTER.Shared.Services.Notifications;
using FVN_REGISTER.Shared.Services.OTs;
using FVN_REGISTER.Shared.Services.Security;
using FVN_REGISTER.Shared.Services.Trips;
using FVN_REGISTER.Shared.Services.Users;
using FVN_REGISTER.Shared.Utils;
using FVN_REGISTER.Web.Components;
using FVN_REGISTER.Web.Services;
using Microsoft.AspNetCore.Components.Authorization;
using MudBlazor;
using MudBlazor.Services;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents().AddInteractiveServerComponents();
builder.Services.AddMudServices(config =>
{
    config.SnackbarConfiguration.PositionClass = Defaults.Classes.Position.BottomRight;
    config.SnackbarConfiguration.MaxDisplayedSnackbars = 4;
    config.SnackbarConfiguration.PreventDuplicates = true;
});
builder.Services.AddBlazoredLocalStorage();
builder.Services.Configure<AuthDebugOptions>(builder.Configuration.GetSection("AuthDebug"));
builder.Services.AddAuthentication(options => options.DefaultScheme = "Cookies").AddCookie("Cookies", options => { options.LoginPath = "/login"; options.AccessDeniedPath = "/access-denied"; });
builder.Services.AddAuthorizationCore(); builder.Services.AddCascadingAuthenticationState();
builder.Services.AddScoped<CustomAuthStateProvider>(); builder.Services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<CustomAuthStateProvider>()); builder.Services.AddScoped<ITokenStorage, LocalStorageTokenService>(); var baseUrl = builder.Configuration["ApiSettings:BaseUrl"] ?? "http://localhost:5017/"; if (!baseUrl.EndsWith("/")) baseUrl += "/";
builder.Services.AddHttpClient<IAuthClientService, AuthClientService>(client => client.BaseAddress = new Uri(baseUrl));
builder.Services.AddHttpClient<IHttpClientWithAuth, AuthorizedHttpClient>(client => client.BaseAddress = new Uri(baseUrl));
builder.Services.AddScoped<ICurrentUserClientService, CurrentUserClientService>();
builder.Services.AddScoped<IDashboardClientService, DashboardClientService>();
builder.Services.AddScoped<ILeaveCreateClientService, LeaveCreateClientService>();
builder.Services.AddScoped<ILeaveHistorysClientService, LeaveHistorysClientService>();
builder.Services.AddScoped<IReportClientService, ReportClientService>();
builder.Services.AddScoped<INotificationClientService, NotificationClientService>();
builder.Services.AddScoped<IDeptClientService, DeptClientService>();
builder.Services.AddScoped<IOTClientService, OTClientService>();
builder.Services.AddScoped<IOTLimitRuleManagementClientService, OTLimitRuleManagementClientService>();
builder.Services.AddScoped<IHrmSyncReviewClientService, HrmSyncReviewClientService>();
builder.Services.AddScoped<IHrmSyncClientService, HrmSyncClientService>();
builder.Services.AddScoped<IHrmAttendanceCalculationClientService, HrmAttendanceCalculationClientService>();
builder.Services.AddScoped<IHrmUserRoleRuleClientService, HrmUserRoleRuleClientService>();
builder.Services.AddScoped<IUserManagementClientService, UserManagementClientService>(); builder.Services.AddScoped<IPasswordResetRequestClientService, PasswordResetRequestClientService>();
builder.Services.AddScoped<ISecurityClientService, SecurityClientService>();
builder.Services.AddScoped<IAccessChangeClientService, AccessChangeClientService>();
builder.Services.AddScoped<IApprovalListClientService, ApprovalListClientService>();
builder.Services.AddScoped<IApproverClientService, ApproverClientService>();
builder.Services.AddScoped<IApprovalRouteClientService, ApprovalRouteClientService>();
builder.Services.AddScoped<IApprovalPolicyClientService, ApprovalPolicyClientService>();
builder.Services.AddScoped<IHistoryClientService, HistoryClientService>();
builder.Services.AddScoped<IDepartmentStatusClientService, DepartmentStatusClientService>();
builder.Services.AddScoped<IEmailTemplateClientService, EmailTemplateClientService>();
builder.Services.AddScoped<IEmailQueueClientService, EmailQueueClientService>();
builder.Services.AddScoped<IEmployeeManagementClientService, EmployeeManagementClientService>();
builder.Services.AddScoped<IDepartmentManagementClientService, DepartmentManagementClientService>();
builder.Services.AddScoped<ILeaveTypeClientService, LeaveTypeClientService>();
builder.Services.AddScoped<ILeaveEntitlementClientService, LeaveEntitlementClientService>();
builder.Services.AddScoped<ITripClientService, TripClientService>(); builder.Services.AddScoped<IWorkCalendarClientService, WorkCalendarClientService>();
builder.Services.AddScoped<IExecutionReconciliationClientService, ExecutionReconciliationClientService>();
builder.Services.AddScoped<IWorkYearManagementClientService, WorkYearManagementClientService>();
builder.Services.AddScoped<ICompanyHolidayManagementClientService, CompanyHolidayManagementClientService>();
builder.Services.AddScoped<FVN_REGISTER.Shared.Services.Equipment.IEquipmentClientService, FVN_REGISTER.Shared.Services.Equipment.EquipmentClientService>();
builder.Services.AddServerSideBlazor().AddCircuitOptions(options => options.DetailedErrors = true);
var app = builder.Build();
if (!app.Environment.IsDevelopment()) { app.UseExceptionHandler("/Error", true); app.UseHsts(); }
app.UseStaticFiles(); app.UseAntiforgery(); app.UseAuthentication(); app.UseAuthorization();
app.MapRazorComponents<App>().AddInteractiveServerRenderMode().AddAdditionalAssemblies(typeof(FVN_REGISTER.Shared.Routes).Assembly);
app.Run();
