using System.Reflection;

namespace FVN_REGISTER.Web.Security;

/// <summary>
/// Manifest generated by the Web host to describe UI operations that may require
/// registration in the central security-function registry.
/// This type is deliberately dependency-free so the Web project can generate a
/// manifest without changing existing business services or authorization logic.
/// </summary>
public sealed record SecurityDiscoveryManifestEntry(
    string FunctionKey,
    string Module,
    string Action,
    string Source,
    string SourceType,
    string? Route,
    string? Component,
    string DisplayName,
    string Description);

public static class SecurityDiscoveryManifestBuilder
{
    private static readonly string[] ActionTokens =
    [
        "Create", "Add", "Edit", "Update", "Delete", "Remove",
        "Approve", "Reject", "Cancel", "Submit", "Save",
        "Import", "Export", "Excel", "Print", "Download", "Upload",
        "Handover", "Transfer", "Return", "Repair", "Sync",
        "Calculate", "Recalculate", "Lock", "Unlock", "Publish",
        "Archive", "Restore", "Reset"
    ];

    public static IReadOnlyList<SecurityDiscoveryManifestEntry> Discover(
        IEnumerable<Assembly> assemblies)
    {
        var result = new List<SecurityDiscoveryManifestEntry>();

        foreach (var assembly in assemblies.Distinct())
        {
            Type[] types;
            try
            {
                types = assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                types = ex.Types.Where(static t => t is not null).Cast<Type>().ToArray();
            }

            foreach (var type in types)
            {
                foreach (var method in type.GetMethods(
                    BindingFlags.Instance | BindingFlags.Static |
                    BindingFlags.Public | BindingFlags.NonPublic |
                    BindingFlags.DeclaredOnly))
                {
                    if (method.IsSpecialName || method.IsConstructor)
                        continue;

                    var token = ActionTokens.FirstOrDefault(x =>
                        method.Name.Contains(x, StringComparison.OrdinalIgnoreCase));

                    if (token is null)
                        continue;

                    var module = type.Namespace?.Split('.').LastOrDefault() ?? "Web";
                    var action = token;
                    var functionKey = $"{module}.{action}";

                    result.Add(new SecurityDiscoveryManifestEntry(
                        functionKey,
                        module,
                        action,
                        assembly.GetName().Name ?? "Web",
                        "UI",
                        null,
                        type.FullName,
                        ToDisplayName(action),
                        ToDescription(action, module)));
                }
            }
        }

        return result
            .GroupBy(x => new { x.FunctionKey, x.Source, x.Component })
            .Select(g => g.First())
            .OrderBy(x => x.FunctionKey, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    private static string ToDisplayName(string action) => action switch
    {
        "Create" or "Add" => "Thêm",
        "Edit" or "Update" => "Cập nhật",
        "Delete" or "Remove" => "Xóa",
        "Approve" => "Phê duyệt",
        "Reject" => "Từ chối",
        "Cancel" => "Hủy",
        "Submit" => "Gửi xử lý",
        "Import" => "Nhập dữ liệu",
        "Export" or "Excel" => "Xuất dữ liệu",
        "Print" => "In",
        "Download" => "Tải xuống",
        "Upload" => "Tải lên",
        "Handover" => "Bàn giao",
        "Transfer" => "Điều chuyển",
        "Return" => "Thu hồi",
        "Repair" => "Sửa chữa",
        "Sync" => "Đồng bộ",
        "Calculate" or "Recalculate" => "Tính toán",
        "Lock" => "Khóa",
        "Unlock" => "Mở khóa",
        "Publish" => "Công bố",
        "Archive" => "Lưu trữ",
        "Restore" => "Khôi phục",
        "Reset" => "Đặt lại",
        _ => action
    };

    private static string ToDescription(string action, string module) =>
        $"Thao tác {ToDisplayName(action).ToLowerInvariant()} của phân hệ {module}.";
}
