<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Utils\Extentions\OTHoursCheckStatusExtensions.cs" />
    <Compile Remove="Utils\Extentions\OTSyncSituationExtensions.cs" />
    <Compile Remove="Utils\Extentions\OTUnconfirmedUIExtensions.cs" />
    <Compile Remove="Utils\Extentions\WorkerRunStateUIExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.6" />
    <PackageReference Include="MudBlazor" Version="9.3.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="Blazored.TextEditor" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\FVN_REGISTER.Application.csproj" />
    <ProjectReference Include="..\..\FVN_REGISTER.Models\FVN_REGISTER.Contract.csproj" />
  </ItemGroup>

</Project>
