USE [FVN_REGISTER];
GO
/* Application login/user is intentionally NOT created here.
   Grant permissions to the SQL login/user created by deployment infrastructure. */
IF DATABASE_PRINCIPAL_ID(N'FVN_REGISTER_APP') IS NULL
BEGIN
    CREATE ROLE [FVN_REGISTER_APP];
END
GO
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::auth TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::hr TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::leave TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::ot TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::trip TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::equipment TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::notify TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::audit TO [FVN_REGISTER_APP];
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::config TO [FVN_REGISTER_APP];
GRANT EXECUTE ON SCHEMA::leave TO [FVN_REGISTER_APP];
GRANT EXECUTE ON SCHEMA::notify TO [FVN_REGISTER_APP];
GO
