USE [FVN_REGISTER];
GO
IF NOT EXISTS(SELECT 1 FROM sys.database_principals WHERE name=N'FVN_REGISTER_APP') CREATE ROLE FVN_REGISTER_APP;
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHEMA::dbo TO FVN_REGISTER_APP;
GRANT EXECUTE ON SCHEMA::dbo TO FVN_REGISTER_APP;
GO
